repo: https://github.com/openwrt/openwrt.git
branch: v19.07.8
git_clone_dir: openwrt-19.07/openwrt-19.07.8
openwrt_root_dir: openwrt-19.07/openwrt-19.07.8
revision: 31f2f76cd5d7745e28fae3797d79b746360461f5

patch_folders:
  - patches-19.07.8/
